### ISSUE TITLE
No way to cancel a one shot timer?

### ISSUE THREAD

**Issue by bradleysmith** [m-peko/thread-utils#6]
I very much like this implementation. However once I've scheduled a timer I see no way to cancel it. The cancel() function appears to only be valid for stopping the next timer in repeating timers. The real issue is that the future that comes back is tied to the async call and if I want to delete that future (because I no longer need the timer) then the delete() will hang until the future  is complete. Or am I missing a trick somewhere?

**Comment by m-peko** [comment]
Hi @bradleysmith,
I am glad you like this implementation. I will try to take a look into this issue as soon as possible.
Best regards

**Comment by m-peko** [comment]
So, the fix is pretty easy.
If I am correct, you are using the following version of `schedule` function:

```
template <typename TimerTask, typename ... Args>
std::future<void> schedule(Delay const& delay, TimerTask task, Args... args) const {
    return std::async(std::launch::async, [=]() {
        std::this_thread::sleep_for(delay);
        std::invoke(task, args...);
    });
}
```

There should be an additional check in the function body if the timer is running still or not like:

```
if (is_running_) {
    std::invoke(task, args...);
}
```

Please let me know if this works for you. I will merge this to master as soon as possible.
Thank you

**Comment by bradleysmith** [comment]
Don't see how that will work. We need to do the sleep_for in order that it doesn't invoke the task. At what point would it check the is_running flag?
I think there's an issue with the other variants too in that you can only cancel the next iteration of the repeating timer; the one currently waiting will not be halted, it still has to fire before the check is made on the is_running flag

**Comment by m-peko** [comment]
So, if I understood you correctly you want your task not to be executed once the timer is cancelled. If that's my correct assumption, then we can check if the `is_running_` flag is set or not once the task is supposed to be executed, like in the below code:

```
template <typename TimerTask, typename ... Args>
std::future<void> schedule(Delay const& delay, TimerTask task, Args... args) const {
    return std::async(std::launch::async, [=]() {
        std::this_thread::sleep_for(delay);
        if (is_running_) {
            std::invoke(task, args...);
        }
    });
}
```

Check live demo [here](https://wandbox.org/permlink/5l3WWX3sPXMp7tHJ).

**Comment by bradleysmith** [comment]
Well, that would indeed stop the task from running. The problem I have is with std::async really. I store scheduled "things" in a map. When someone wants to schedule something I create one of these "things", call your Time with the callback and store the returned future in the "thing". The thing then gets put in the map. At some poing someone changestheir mind and wants to unschedule that thing. So, what I really want to do is delete my "thing" form the map. But I can't because it holds the returned futuren so trying to delete it before the future comes back will cause the program to halt until the future is returned.

I'm not sure there's anything you can do to fix it really. I don't even care about the returned future but std::async doesn't support me not caring about it :-)

I could fix it my end by having some global list where I keep the futures and never delete them until they complete. Seems hacky.

**Comment by bradleysmith** [comment]
I added this function to my local version, which does what I want:

`    /**
     * Schedules the specified task for execution at the specified time.
     * Less accurate that regular schedule
     * Can be aborted by calling cancel
     *
     * @param time Time at which task is to be executed
     * @param task Task to be scheduled
     * @param args Arguments to be passed to the specified task
     *
     * @return Result of the task
     */
    template <typename TimerTask, typename ... Args>
    std::future<void> abortable_schedule(Timestamp const& time, TimerTask task, Args... args) const {
        return std::async(std::launch::async, [=]() {
            auto start = std::chrono::time_point_cast<Timestamp::duration>(std::chrono::system_clock::now());
            auto delay = std::chrono::duration_cast<Delay>(time - start);
            while(is_running_ && (std::chrono::system_clock::now() < time))
            {
                std::this_thread::sleep_for(std::chrono::seconds(1));
            }
            if(is_running_)
            {
                std::invoke(task, args...);
            }
            // else we got cancelled
        });
    }
`

**Comment by m-peko** [comment]
What if the difference between `time` and `...::now()` is in milliseconds or microseconds? Then you will sleep for 1 second which is not correct. Timer should be sleeping for that exact amount of milliseconds/microseconds. Also, I think you don't actually need that `while` loop. Simple if condition would work too.

**Comment by bradleysmith** [comment]
Yes I did say in the comments that this was less accurate. I don’t need sub second accuracy for this particular application.

It does need the while loop. Imagine waiting for an hour to trigger. It would check the if condition once, sleep for a second and then invoke! The while loop causes it to sleep for one second intervals and each time it gets the chance to see whether it has been cancelled or not and when now >= invoke time it invokes.

**Comment by m-peko** [comment]
Yes, you are right. Anyway, if you want to make an update to the existing `Timer` functions, please feel free.
Thank you and best regards
