### ISSUE TITLE
Explicitly defaulted copy constructor is implicitly deleted

### ISSUE THREAD

**Issue by donRumata03** [m-peko/thread-utils#7]
https://github.com/m-peko/thread-utils/blob/b3e541b286cc6cdd27e4e8b575886df913396433/utils/timer.hpp#L53

"Explicitly defaulted copy constructor is implicitly deleted", because std::atomic objects are not copyable.

`atomic(const atomic&) = delete;` <- from STL

**Comment by donRumata03** [comment]
There`s the same problem here:

https://github.com/m-peko/thread-utils/blob/b3e541b286cc6cdd27e4e8b575886df913396433/utils/timer.hpp#L50

**Comment by m-peko** [comment]
@donRumata03 thanks for reporting the issue. It is fixed now. Feel free to contribute yourself in the future with any extension you want :smile:
